### ISSUE TITLE
Errors about audio_devices.index(default_device)

### ISSUE THREAD

**Issue by bg4xsd** [f4exb/morseangel#1]
Env:
both python 3.7.16 and python 3.9.15, windows 11 64bit
pip install -r requirements.txt,  and install torch =1.13.1, pyqt5= 5.15.8
python ./morseangel.py
The main GUI appears while choosing the device menu item, throwing an error, and exit.

Error message:
Torch using cpu
MorseDecoderRegen.__init__: 11.0 23.0 25.0
Init zenv 50
Traceback (most recent call last):
  File "./morseangel.py", line 374, in openAudioDialog
    self.audio_dialog.set_audio_devices(self.audio_devices)
  File "d:\myWork\cwlab_intra\morseangel\audiodialog.py", line 35, in set_audio_devices
    self.default_device_index = audio_devices.index(default_device)
ValueError: <PyQt5.QtMultimedia.QAudioDeviceInfo object at 0x000001A639E2F128> is not in list

I try to trace the error. 
First test: 
Directly run below cmd:
audio_devices = get_audioin_devices()
for device in audio_devices :
    print(device.deviceName(), device)

The output is 
Microphone (USB MIC    ) <PyQt5.QtMultimedia.QAudioDeviceInfo object at 0x000001F73C6C0198>
Line 1 (Virtual Audio Cable) <PyQt5.QtMultimedia.QAudioDeviceInfo object at 0x000001F73C6C00B8>
Microphone(HD Webcam C525) <PyQt5.QtMultimedia.QAudioDeviceInfo object at 0x000001F73C6C0EB8>
Microphone(USB MIC    ) <PyQt5.QtMultimedia.QAudioDeviceInfo object at 0x000001F73C6C0F28>
Line 1 (Virtual Audio Cable) <PyQt5.QtMultimedia.QAudioDeviceInfo object at 0x000001F73C6C0DD8>
Microphone(HD Webcam C525) <PyQt5.QtMultimedia.QAudioDeviceInfo object at 0x000001F73C6C03C8>

audio_device = QtMultimedia.QAudioDeviceInfo.defaultInputDevice()
audio_device  is  <PyQt5.QtMultimedia.QAudioDeviceInfo at 0x1f73c199ac8>
                  in another run, return is  <PyQt5.QtMultimedia.QAudioDeviceInfo at 0x1f73dea7748>
but it is very stranger, defaultInputDevice() returns will change, and return objects in a different format

So, the function set_audio_devices throws an error
    def set_audio_devices(self, audio_devices):
        self.audio_devices = audio_devices
        device_names = [device.deviceName() for device in audio_devices]   # it works ok, and returns the correct device name
        self.deviceCombo.blockSignals(True)
        self.deviceCombo.addItems(device_names)
        self.deviceCombo.blockSignals(False)
        default_device = QtMultimedia.QAudioDeviceInfo.defaultInputDevice() # it DO works, but the return seems wrong
        self.default_device_index = audio_devices.index(default_device) # ERROR 
        self.deviceCombo.setCurrentIndex(self.default_device_index)

**Comment by bg4xsd** [comment]
The code works well on Ubuntu 20.04, and 22.04, but windows.  So, I think working with Linux is a better choice.

**Comment by bg4xsd** [comment]
For windows 11, python=3.9.16, pyqt5=5.15.9, torch=1.13.1

A few changes on the original codes, upload as a zip file. The code is running with some time delay, maybe I should upgrade my workstation, :)

I hope it is helpful, have fun.

[patch4win11.zip](https://github.com/f4exb/morseangel/files/10694419/patch4win11.zip)
![Screenshot 2023-02-09 151121](https://user-images.githubusercontent.com/29818247/217743212-a24406c6-bfc1-47a0-9a30-f3752991c30c.png)
