### ISSUE TITLE
Issue with devices on W11?

### ISSUE THREAD

**Issue by ogameus** [f4exb/morseangel#3]
I just started the program its W11 platform, and I haven't got to bar in normal colors (like inactive or something), after clicking on devices, the program just turns off. Below I post screen and command line after clicking the Devices in program

[
![Bez tytułu](https://github.com/user-attachments/assets/5b4b9ea8-f3e4-4810-a707-929963fa0a9c)
](url)

`PS C:\Users\SQ8M\Downloads\morseangel-main> python .\morseangel.py`
`Torch using cpu`
`MorseDecoderRegen.__init__: 11.0 23.0 25.0`
`Init zenv 50`
`Traceback (most recent call last):`
    `File "C:\Users\SQ8M\Downloads\morseangel-main\morseangel.py", line 374, in openAudioDialog
    self.audio_dialog.set_audio_devices(self.audio_devices)`
 ` File "C:\Users\SQ8M\Downloads\morseangel-main\audiodialog.py", line 35, in set_audio_devices
    self.default_device_index = audio_devices.index(default_device)`
                            `    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`
`ValueError: <PyQt5.QtMultimedia.QAudioDeviceInfo object at 0x0000024D9A8E0A50> is not in list`

Best regards,
Mateusz SQ8M

**Comment by SkyPi-hash** [comment]
I would like to second this issue.

**Comment by StefanKDS** [comment]
Maybe to late but here is the solution for the problems above in Win11:

1. Avoid White Background:

morseangel.py

Replace the _main()_ function with these code:

```
def main():
    app = QtWidgets.QApplication(sys.argv)
    app.setPalette(make_palette())
    app.setStyleSheet("""
            QMenuBar {
                background-color: #2b2b2b;
                color: white;
            }
            QMenuBar::item:selected {
                background-color: #444444;
            }
            QMenu {
                background-color: #2b2b2b;
                color: white;
            }
            QMenu::item:selected {
                background-color: #444444;
            }
            QPushButton {
                background-color: #444444;
                color: white;
                border: 1px solid #666;
                padding: 4px;
            }
            QPushButton::hover {
                background-color: #555555;
            }
            QTextEdit {
                background-color: #1e1e1e;
                color: white;
            }
            QLabel {
                color: white;
            }
            QStatusBar {
                background-color: #2b2b2b;
                color: white;
            }
        """)
    w = MainWindow()
    sys.exit(app.exec_())
```

2. Crash when open Device dialog:

audiodialog.py

replace the _set_audio_devices(self, audio_devices)_ function with these code:

   ```
 def set_audio_devices(self, audio_devices):
        if not audio_devices:
            QtWidgets.QMessageBox.critical(self, "Error", "No audio devices found.")
            self.reject()
            return

        self.audio_devices = audio_devices
        device_names = [device.deviceName() for device in audio_devices]
        self.deviceCombo.blockSignals(True)
        self.deviceCombo.addItems(device_names)
        self.deviceCombo.blockSignals(False)
        default_device = QtMultimedia.QAudioDeviceInfo.defaultInputDevice()
        if default_device in audio_devices:
            self.default_device_index = audio_devices.index(default_device)
            self.deviceCombo.setCurrentIndex(self.default_device_index)
        else:
            self.default_device_index = -1  # oder 0 als fallback
        self.deviceCombo.setCurrentIndex(self.default_device_index)
```


In case of problems let me know

**Comment by csylvain** [comment]
it runs in WSL2. select "pulse" for the audio device.
